# Generated by Django 3.0.6 on 2022-02-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.BigIntegerField(blank=True, db_column='Fever', null=True)),
                ('tiredness', models.IntegerField(blank=True, db_column='Tiredness', null=True)),
                ('dry_cough', models.IntegerField(blank=True, db_column='Dry-Cough', null=True)),
                ('difficulty_in_breathing', models.IntegerField(blank=True, db_column='Difficulty-in-Breathing', null=True)),
                ('sore_throat', models.IntegerField(blank=True, db_column='Sore-Throat', null=True)),
                ('none_sympton', models.IntegerField(blank=True, db_column='None_Sympton', null=True)),
                ('pains', models.IntegerField(blank=True, db_column='Pains', null=True)),
                ('nasal_congestion', models.IntegerField(blank=True, db_column='Nasal-Congestion', null=True)),
                ('runny_nose', models.IntegerField(blank=True, db_column='Runny-Nose', null=True)),
                ('diarrhea', models.IntegerField(blank=True, db_column='Diarrhea', null=True)),
                ('none_experiencing', models.IntegerField(blank=True, db_column='None_Experiencing', null=True)),
                ('age_0_9', models.IntegerField(blank=True, db_column='Age_0-9', null=True)),
                ('age_10_19', models.IntegerField(blank=True, db_column='Age_10-19', null=True)),
                ('age_20_24', models.IntegerField(blank=True, db_column='Age_20-24', null=True)),
                ('age_25_59', models.IntegerField(blank=True, db_column='Age_25-59', null=True)),
                ('age_60_field', models.IntegerField(blank=True, db_column='Age_60+', null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=255, null=True)),
                ('severity_mild', models.IntegerField(blank=True, db_column='Severity_Mild', null=True)),
                ('severity_moderate', models.IntegerField(blank=True, db_column='Severity_Moderate', null=True)),
                ('severity_severe', models.IntegerField(blank=True, db_column='Severity_Severe', null=True)),
                ('contact_1es', models.IntegerField(blank=True, db_column='Co0tact_1es', null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=255, null=True)),
            ],
            options={
                'db_table': 'sym',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='China',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.BigIntegerField(blank=True, null=True)),
                ('tiredness', models.IntegerField(blank=True, null=True)),
                ('dry_cough', models.IntegerField(blank=True, null=True)),
                ('difficulty_in_breathing', models.IntegerField(blank=True, null=True)),
                ('sore_throat', models.IntegerField(blank=True, null=True)),
                ('none_sympton', models.IntegerField(blank=True, null=True)),
                ('pains', models.IntegerField(blank=True, null=True)),
                ('nasal_congestion', models.IntegerField(blank=True, null=True)),
                ('runny_nose', models.IntegerField(blank=True, null=True)),
                ('diarrhea', models.IntegerField(blank=True, null=True)),
                ('none_experiencing', models.IntegerField(blank=True, null=True)),
                ('age_0_9', models.IntegerField(blank=True, null=True)),
                ('age_10_19', models.IntegerField(blank=True, null=True)),
                ('age_20_24', models.IntegerField(blank=True, null=True)),
                ('age_25_59', models.IntegerField(blank=True, null=True)),
                ('age_60_field', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('severity_mild', models.IntegerField(blank=True, null=True)),
                ('severity_moderate', models.IntegerField(blank=True, null=True)),
                ('severity_severe', models.IntegerField(blank=True, null=True)),
                ('contact_1es', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'China',
            },
        ),
    ]
