# Generated by Django 3.0.6 on 2022-03-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sym_all',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255, null=True)),
                ('allperson', models.IntegerField(blank=True, null=True)),
                ('male', models.IntegerField(blank=True, null=True)),
                ('female', models.IntegerField(blank=True, null=True)),
                ('fever', models.BigIntegerField(blank=True, null=True)),
                ('tiredness', models.IntegerField(blank=True, null=True)),
                ('drycough', models.IntegerField(blank=True, null=True)),
                ('difficultybreathing', models.IntegerField(blank=True, null=True)),
                ('sorethroat', models.IntegerField(blank=True, null=True)),
                ('nonesympton', models.IntegerField(blank=True, null=True)),
                ('pains', models.IntegerField(blank=True, null=True)),
                ('nasalcongestion', models.IntegerField(blank=True, null=True)),
                ('runnynose', models.IntegerField(blank=True, null=True)),
                ('diarrhea', models.IntegerField(blank=True, null=True)),
                ('noneexperiencing', models.IntegerField(blank=True, null=True)),
                ('age09', models.IntegerField(blank=True, null=True)),
                ('age1019', models.IntegerField(blank=True, null=True)),
                ('age2024', models.IntegerField(blank=True, null=True)),
                ('age2559', models.IntegerField(blank=True, null=True)),
                ('age60field', models.IntegerField(blank=True, null=True)),
                ('severitymild', models.IntegerField(blank=True, null=True)),
                ('severitymoderate', models.IntegerField(blank=True, null=True)),
                ('severitysevere', models.IntegerField(blank=True, null=True)),
                ('contactor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sym_all',
            },
        ),
        migrations.AlterModelOptions(
            name='sym',
            options={},
        ),
        migrations.RenameField(
            model_name='china',
            old_name='age_0_9',
            new_name='age09',
        ),
        migrations.RenameField(
            model_name='china',
            old_name='age_10_19',
            new_name='age1019',
        ),
        migrations.RenameField(
            model_name='china',
            old_name='age_20_24',
            new_name='age2024',
        ),
        migrations.RenameField(
            model_name='china',
            old_name='age_25_59',
            new_name='age2559',
        ),
        migrations.RenameField(
            model_name='china',
            old_name='age_60_field',
            new_name='age60field',
        ),
        migrations.RenameField(
            model_name='china',
            old_name='contact_1es',
            new_name='contactyes',
        ),
        migrations.RenameField(
            model_name='china',
            old_name='difficulty_in_breathing',
            new_name='difficultybreathing',
        ),
        migrations.RenameField(
            model_name='china',
            old_name='dry_cough',
            new_name='drycough',
        ),
        migrations.RenameField(
            model_name='china',
            old_name='nasal_congestion',
            new_name='nasalcongestion',
        ),
        migrations.RenameField(
            model_name='china',
            old_name='none_experiencing',
            new_name='noneexperiencing',
        ),
        migrations.RenameField(
            model_name='china',
            old_name='none_sympton',
            new_name='nonesympton',
        ),
        migrations.RenameField(
            model_name='china',
            old_name='runny_nose',
            new_name='runnynose',
        ),
        migrations.RenameField(
            model_name='china',
            old_name='severity_mild',
            new_name='severitymild',
        ),
        migrations.RenameField(
            model_name='china',
            old_name='severity_moderate',
            new_name='severitymoderate',
        ),
        migrations.RenameField(
            model_name='china',
            old_name='severity_severe',
            new_name='severitysevere',
        ),
        migrations.RenameField(
            model_name='china',
            old_name='sore_throat',
            new_name='sorethroat',
        ),
    ]
