# Generated by Django 3.0.6 on 2022-03-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sym', '0002_auto_20220311_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='china',
            old_name='age60field',
            new_name='age60',
        ),
        migrations.RemoveField(
            model_name='sym',
            name='age_0_9',
        ),
        migrations.RemoveField(
            model_name='sym',
            name='age_10_19',
        ),
        migrations.RemoveField(
            model_name='sym',
            name='age_20_24',
        ),
        migrations.RemoveField(
            model_name='sym',
            name='age_25_59',
        ),
        migrations.RemoveField(
            model_name='sym',
            name='age_60_field',
        ),
        migrations.RemoveField(
            model_name='sym',
            name='contact_1es',
        ),
        migrations.RemoveField(
            model_name='sym',
            name='difficulty_in_breathing',
        ),
        migrations.RemoveField(
            model_name='sym',
            name='dry_cough',
        ),
        migrations.RemoveField(
            model_name='sym',
            name='nasal_congestion',
        ),
        migrations.RemoveField(
            model_name='sym',
            name='none_experiencing',
        ),
        migrations.RemoveField(
            model_name='sym',
            name='none_sympton',
        ),
        migrations.RemoveField(
            model_name='sym',
            name='runny_nose',
        ),
        migrations.RemoveField(
            model_name='sym',
            name='severity_mild',
        ),
        migrations.RemoveField(
            model_name='sym',
            name='severity_moderate',
        ),
        migrations.RemoveField(
            model_name='sym',
            name='severity_severe',
        ),
        migrations.RemoveField(
            model_name='sym',
            name='sore_throat',
        ),
        migrations.AddField(
            model_name='sym',
            name='age09',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym',
            name='age1019',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym',
            name='age2024',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym',
            name='age2559',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym',
            name='age60',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym',
            name='contactyes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym',
            name='difficultybreathing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym',
            name='drycough',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym',
            name='nasalcongestion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym',
            name='noneexperiencing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym',
            name='nonesympton',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym',
            name='runnynose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym',
            name='severitymild',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym',
            name='severitymoderate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym',
            name='severitysevere',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym',
            name='sorethroat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sym',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sym',
            name='diarrhea',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sym',
            name='fever',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sym',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sym',
            name='pains',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sym',
            name='tiredness',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
