# Generated by Django 3.0.6 on 2022-03-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sym', '0004_france_germany_iran_italy_republicofkorean_spain_uae'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.CharField(blank=True, db_column='Fever', max_length=255, null=True)),
                ('tiredness', models.CharField(blank=True, db_column='Tiredness', max_length=255, null=True)),
                ('drycough', models.CharField(blank=True, db_column='DryCough', max_length=255, null=True)),
                ('difficultybreathing', models.CharField(blank=True, db_column='DifficultyBreathing', max_length=255, null=True)),
                ('sorethroat', models.CharField(blank=True, db_column='SoreThroat', max_length=255, null=True)),
                ('nonesympton', models.CharField(blank=True, db_column='NoneSympton', max_length=255, null=True)),
                ('pains', models.CharField(blank=True, db_column='Pains', max_length=255, null=True)),
                ('nasalcongestion', models.CharField(blank=True, db_column='NasalCongestion', max_length=255, null=True)),
                ('runnynose', models.CharField(blank=True, db_column='RunnyNose', max_length=255, null=True)),
                ('diarrhea', models.CharField(blank=True, db_column='Diarrhea', max_length=255, null=True)),
                ('noneexperiencing', models.CharField(blank=True, db_column='NoneExperiencing', max_length=255, null=True)),
                ('age09', models.CharField(blank=True, db_column='Age09', max_length=255, null=True)),
                ('age1019', models.CharField(blank=True, db_column='Age1019', max_length=255, null=True)),
                ('age2024', models.CharField(blank=True, db_column='Age2024', max_length=255, null=True)),
                ('age2559', models.CharField(blank=True, db_column='Age2559', max_length=255, null=True)),
                ('age60', models.CharField(blank=True, db_column='Age60', max_length=255, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=255, null=True)),
                ('severitymild', models.CharField(blank=True, db_column='SeverityMild', max_length=255, null=True)),
                ('severitymoderate', models.CharField(blank=True, db_column='SeverityModerate', max_length=255, null=True)),
                ('severitysevere', models.CharField(blank=True, db_column='SeveritySevere', max_length=255, null=True)),
                ('contactyes', models.CharField(blank=True, db_column='Contactyes', max_length=255, null=True)),
            ],
            options={
                'db_table': 'other',
                'managed': False,
            },
        ),
    ]
