# Generated by Django 3.0.6 on 2022-03-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sym', '0005_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='sym_all',
            name='age090',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym_all',
            name='age091',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym_all',
            name='age10190',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym_all',
            name='age10191',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym_all',
            name='age20240',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym_all',
            name='age20241',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym_all',
            name='age25590',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym_all',
            name='age25591',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym_all',
            name='age60field0',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sym_all',
            name='age60field1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
