# Generated by Django 3.0.6 on 2022-05-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sym', '0006_auto_20220314_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sym0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.BigIntegerField(blank=True, null=True)),
                ('tiredness', models.IntegerField(blank=True, null=True)),
                ('drycough', models.IntegerField(blank=True, null=True)),
                ('difficultybreathing', models.IntegerField(blank=True, null=True)),
                ('sorethroat', models.IntegerField(blank=True, null=True)),
                ('nonesympton', models.IntegerField(blank=True, null=True)),
                ('pains', models.IntegerField(blank=True, null=True)),
                ('nasalcongestion', models.IntegerField(blank=True, null=True)),
                ('runnynose', models.IntegerField(blank=True, null=True)),
                ('diarrhea', models.IntegerField(blank=True, null=True)),
                ('noneexperiencing', models.IntegerField(blank=True, null=True)),
                ('age09', models.IntegerField(blank=True, null=True)),
                ('age1019', models.IntegerField(blank=True, null=True)),
                ('age2024', models.IntegerField(blank=True, null=True)),
                ('age2559', models.IntegerField(blank=True, null=True)),
                ('age60', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('severitymild', models.IntegerField(blank=True, null=True)),
                ('severitymoderate', models.IntegerField(blank=True, null=True)),
                ('severitysevere', models.IntegerField(blank=True, null=True)),
                ('contactyes', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sym0',
            },
        ),
    ]
