from django.db import models

# Create your models here.
class patient(models.Model):
    id = models.BigAutoField(primary_key=True)
    sex = models.CharField(max_length=255, blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    patient_type = models.CharField(max_length=255, blank=True, null=True)
    infect = models.CharField(max_length=255, blank=True, null=True)
    icu = models.CharField(max_length=255, blank=True, null=True)
    dead = models.CharField(max_length=255, blank=True, null=True)
    chaguan = models.CharField(max_length=255, blank=True, null=True)
    feiyan = models.CharField(max_length=255, blank=True, null=True)
    renshen = models.CharField(max_length=255, blank=True, null=True)
    tangniaobing = models.CharField(max_length=255, blank=True, null=True)
    feiqizhong = models.CharField(max_length=255, blank=True, null=True)
    xiaochuan = models.CharField(max_length=255, blank=True, null=True)
    gaoxueya = models.CharField(max_length=255, blank=True, null=True)
    xinxueguan = models.CharField(max_length=255, blank=True, null=True)
    feipang = models.CharField(max_length=255, blank=True, null=True)
    shenshuaijie = models.CharField(max_length=255, blank=True, null=True)
    smoking = models.CharField(max_length=255, blank=True, null=True)
    contacts = models.CharField(max_length=255, blank=True, null=True)
    other = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'patient'
class pa_organ(models.Model):
    heart = models.IntegerField(blank=True, null=True)
    spleen =models.IntegerField(blank=True, null=True)
    kidney =models.IntegerField(blank=True, null=True)
    lung =models.IntegerField(blank=True, null=True)
    liver =models.IntegerField(blank=True, null=True)
    other =models.IntegerField(blank=True, null=True)
    time=models.DateTimeField(auto_now=True)
    class Meta:
        db_table='pa_organ'
class patient_pca(models.Model):
    pfeiyan=models.FloatField(blank=True,null=True)
    prenshen=models.FloatField(blank=True,null=True)
    ptangniaobing=models.FloatField(blank=True,null=True)
    pfeiqizhong=models.FloatField(blank=True,null=True)
    pxiaochuan=models.FloatField(blank=True,null=True)
    pgaoxueya=models.FloatField(blank=True,null=True)
    pxinxueguan=models.FloatField(blank=True,null=True)
    pfeipang=models.FloatField(blank=True,null=True)
    pshenshuaijie=models.FloatField(blank=True,null=True)
    psmoking=models.FloatField(blank=True,null=True)
    pcontacts=models.FloatField(blank=True,null=True)
    pother=models.FloatField(blank=True,null=True)
    class Meta:
        db_table="patient_pca"
class total(models.Model):
    id = models.BigAutoField(primary_key=True)
    male=models.IntegerField(blank=True, null=True)
    female=models.IntegerField(blank=True, null=True)
    children=models.IntegerField(blank=True, null=True)
    young=models.IntegerField(blank=True, null=True)
    adults=models.IntegerField(blank=True, null=True)
    older=models.IntegerField(blank=True, null=True)
    childrenN =models.IntegerField(blank=True, null=True)
    youngN = models.IntegerField(blank=True, null=True)
    adultsN =models.IntegerField(blank=True, null=True)
    olderN=models.IntegerField(blank=True, null=True)
    patienin=models.IntegerField(blank=True, null=True)
    patienout=models.IntegerField(blank=True, null=True)
    infectY=models.IntegerField(blank=True, null=True)
    all=models.IntegerField(blank=True, null=True)
    icuY=models.IntegerField(blank=True, null=True)
    deadY=models.IntegerField(blank=True, null=True)
    deadN=models.IntegerField(blank=True, null=True)
    chaguan=models.IntegerField(blank=True, null=True)
    feiyan=models.IntegerField(blank=True, null=True)
    renshen=models.IntegerField(blank=True, null=True)
    tangniaobing=models.IntegerField(blank=True, null=True)
    feiqizhong =models.IntegerField(blank=True, null=True)
    xiaochuan =models.IntegerField(blank=True, null=True)
    gaoxueya=models.IntegerField(blank=True, null=True)
    xinxueguan=models.IntegerField(blank=True, null=True)
    feipang =models.IntegerField(blank=True, null=True)
    shenshuaijie=models.IntegerField(blank=True, null=True)
    smoking=models.IntegerField(blank=True, null=True)
    contacts =models.IntegerField(blank=True, null=True)
    other=models.IntegerField(blank=True, null=True)
    pfeiyan=models.FloatField(blank=True,null=True)
    prenshen=models.FloatField(blank=True,null=True)
    ptangniaobing=models.FloatField(blank=True,null=True)
    pfeiqizhong=models.FloatField(blank=True,null=True)
    pxiaochuan=models.FloatField(blank=True,null=True)
    pgaoxueya=models.FloatField(blank=True,null=True)
    pxinxueguan=models.FloatField(blank=True,null=True)
    pfeipang=models.FloatField(blank=True,null=True)
    pshenshuaijie=models.FloatField(blank=True,null=True)
    psmoking=models.FloatField(blank=True,null=True)
    pcontacts=models.FloatField(blank=True,null=True)
    pother=models.FloatField(blank=True,null=True)
    class Meta:
        db_table="patient_total"

