# Generated by Django 3.0.6 on 2022-02-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('patient_type', models.CharField(blank=True, max_length=255, null=True)),
                ('infect', models.CharField(blank=True, max_length=255, null=True)),
                ('icu', models.CharField(blank=True, max_length=255, null=True)),
                ('dead', models.CharField(blank=True, max_length=255, null=True)),
                ('chaguan', models.CharField(blank=True, max_length=255, null=True)),
                ('feiyan', models.CharField(blank=True, max_length=255, null=True)),
                ('renshen', models.CharField(blank=True, max_length=255, null=True)),
                ('tangniaobing', models.CharField(blank=True, max_length=255, null=True)),
                ('feiqizhong', models.CharField(blank=True, max_length=255, null=True)),
                ('xiaochuan', models.CharField(blank=True, max_length=255, null=True)),
                ('gaoxueya', models.CharField(blank=True, max_length=255, null=True)),
                ('xinxueguan', models.CharField(blank=True, max_length=255, null=True)),
                ('feipang', models.CharField(blank=True, max_length=255, null=True)),
                ('shenshuaijie', models.CharField(blank=True, max_length=255, null=True)),
                ('smoking', models.CharField(blank=True, max_length=255, null=True)),
                ('contacts', models.CharField(blank=True, max_length=255, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'covid',
                'managed': False,
            },
        ),
    ]
