# Generated by Django 3.0.6 on 2022-02-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pa_organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart', models.IntegerField(max_length=255)),
                ('spleen', models.IntegerField(max_length=255)),
                ('kidney', models.IntegerField(max_length=255)),
                ('lung', models.IntegerField(max_length=255)),
                ('liver', models.IntegerField(max_length=255)),
                ('other', models.IntegerField(max_length=255)),
            ],
            options={
                'db_table': 'pa_organ',
            },
        ),
    ]
