# Generated by Django 3.0.6 on 2022-02-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_pa_organ'),
    ]

    operations = [
        migrations.AddField(
            model_name='pa_organ',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
