# Generated by Django 3.0.6 on 2022-02-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_pa_organ_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pa_organ',
            name='heart',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pa_organ',
            name='kidney',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pa_organ',
            name='liver',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pa_organ',
            name='lung',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pa_organ',
            name='other',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pa_organ',
            name='spleen',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
