# Generated by Django 3.0.6 on 2022-02-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20220215_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('patient_type', models.CharField(blank=True, max_length=255, null=True)),
                ('infect', models.CharField(blank=True, max_length=255, null=True)),
                ('icu', models.CharField(blank=True, max_length=255, null=True)),
                ('dead', models.CharField(blank=True, max_length=255, null=True)),
                ('chaguan', models.CharField(blank=True, max_length=255, null=True)),
                ('feiyan', models.CharField(blank=True, max_length=255, null=True)),
                ('renshen', models.CharField(blank=True, max_length=255, null=True)),
                ('tangniaobing', models.CharField(blank=True, max_length=255, null=True)),
                ('feiqizhong', models.CharField(blank=True, max_length=255, null=True)),
                ('xiaochuan', models.CharField(blank=True, max_length=255, null=True)),
                ('gaoxueya', models.CharField(blank=True, max_length=255, null=True)),
                ('xinxueguan', models.CharField(blank=True, max_length=255, null=True)),
                ('feipang', models.CharField(blank=True, max_length=255, null=True)),
                ('shenshuaijie', models.CharField(blank=True, max_length=255, null=True)),
                ('smoking', models.CharField(blank=True, max_length=255, null=True)),
                ('contacts', models.CharField(blank=True, max_length=255, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='total',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('male', models.IntegerField(max_length=255)),
                ('female', models.IntegerField(max_length=255)),
                ('children', models.IntegerField(max_length=255)),
                ('young', models.IntegerField(max_length=255)),
                ('adults', models.IntegerField(max_length=255)),
                ('older', models.IntegerField(max_length=255)),
                ('childrenN', models.IntegerField(max_length=255)),
                ('youngN', models.IntegerField(max_length=255)),
                ('adultsN', models.IntegerField(max_length=255)),
                ('olderN', models.IntegerField(max_length=255)),
                ('patienin', models.IntegerField(max_length=255)),
                ('patienout', models.IntegerField(max_length=255)),
                ('infectY', models.IntegerField(max_length=255)),
                ('all', models.IntegerField(max_length=255)),
                ('icuY', models.IntegerField(max_length=255)),
                ('deadY', models.IntegerField(max_length=255)),
                ('deadN', models.IntegerField(max_length=255)),
                ('chaguan', models.IntegerField(max_length=255)),
                ('feiyan', models.IntegerField(max_length=255)),
                ('renshen', models.IntegerField(max_length=255)),
                ('tangniaobing', models.IntegerField(max_length=255)),
                ('feiqizhong', models.IntegerField(max_length=255)),
                ('xiaochuan', models.IntegerField(max_length=255)),
                ('gaoxueya', models.IntegerField(max_length=255)),
                ('xinxueguan', models.IntegerField(max_length=255)),
                ('feipang', models.IntegerField(max_length=255)),
                ('shenshuaijie', models.IntegerField(max_length=255)),
                ('smoking', models.IntegerField(max_length=255)),
                ('contacts', models.IntegerField(max_length=255)),
                ('other', models.IntegerField(max_length=255)),
            ],
            options={
                'db_table': 'patient_total',
            },
        ),
        migrations.DeleteModel(
            name='Covid',
        ),
    ]
