# Generated by Django 3.0.6 on 2022-02-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20220227_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='adultsN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='all',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='chaguan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='childrenN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='contacts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='deadN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='deadY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='feipang',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='feiqizhong',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='feiyan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='gaoxueya',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='icuY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='infectY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='older',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='olderN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='other',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='patienin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='patienout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='renshen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='shenshuaijie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='smoking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='tangniaobing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='xiaochuan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='xinxueguan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='young',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='total',
            name='youngN',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
