# Generated by Django 3.0.6 on 2022-03-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20220227_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_pca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfeiyan', models.FloatField(blank=True, null=True)),
                ('prenshen', models.FloatField(blank=True, null=True)),
                ('ptangniaobing', models.FloatField(blank=True, null=True)),
                ('pfeiqizhong', models.FloatField(blank=True, null=True)),
                ('pxiaochuan', models.FloatField(blank=True, null=True)),
                ('pgaoxueya', models.FloatField(blank=True, null=True)),
                ('pxinxueguan', models.FloatField(blank=True, null=True)),
                ('pfeipang', models.FloatField(blank=True, null=True)),
                ('pshenshuaijie', models.FloatField(blank=True, null=True)),
                ('psmoking', models.FloatField(blank=True, null=True)),
                ('pcontacts', models.FloatField(blank=True, null=True)),
                ('pother', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient_pca',
            },
        ),
        migrations.AddField(
            model_name='total',
            name='pcontacts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='pfeipang',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='pfeiqizhong',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='pfeiyan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='pgaoxueya',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='pother',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='prenshen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='pshenshuaijie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='psmoking',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='ptangniaobing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='pxiaochuan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='total',
            name='pxinxueguan',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
