# Generated by Django 3.0.6 on 2022-03-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20220308_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total',
            old_name='pcontacts',
            new_name='pcontact',
        ),
    ]
