# Generated by Django 3.0.6 on 2022-03-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20220310_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_pca',
            old_name='pcontacts',
            new_name='pcontactor',
        ),
    ]
