# Generated by Django 3.0.6 on 2022-03-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_auto_20220310_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_pca',
            old_name='pcontactor',
            new_name='pcontacts',
        ),
        migrations.RenameField(
            model_name='total',
            old_name='pcontact',
            new_name='pcontacts',
        ),
    ]
