# Generated by Django 3.0.6 on 2022-05-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_auto_20220311_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid0',
            fields=[
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('sex', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_type', models.CharField(blank=True, max_length=255, null=True)),
                ('dead', models.CharField(blank=True, max_length=255, null=True)),
                ('chaguan', models.CharField(blank=True, max_length=255, null=True)),
                ('feiyan', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('renshen', models.CharField(blank=True, max_length=255, null=True)),
                ('tangniaobing', models.CharField(blank=True, max_length=255, null=True)),
                ('feiqizhong', models.CharField(blank=True, max_length=255, null=True)),
                ('xiaochuan', models.CharField(blank=True, max_length=255, null=True)),
                ('gaoxueya', models.CharField(blank=True, max_length=255, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('xinxueguan', models.CharField(blank=True, max_length=255, null=True)),
                ('feipang', models.CharField(blank=True, max_length=255, null=True)),
                ('shenshuaijie', models.CharField(blank=True, max_length=255, null=True)),
                ('smoking', models.CharField(blank=True, max_length=255, null=True)),
                ('contacts', models.CharField(blank=True, max_length=255, null=True)),
                ('infect', models.CharField(blank=True, max_length=255, null=True)),
                ('icu', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'covid0',
                'managed': False,
            },
        ),
    ]
